"""add last_active_date to student_profiles

Revision ID: d74a053fda8f
Revises: 106858809516
Create Date: 2026-06-15 09:16:40.402916
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74a053fda8f'
down_revision: Union[str, None] = '106858809516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('last_active_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'last_active_date')
    # ### end Alembic commands ###
